# Generated by Django 3.2 on 2022-11-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='pan',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='work',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='work',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='work',
            name='company',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='work',
            name='postalZip',
            field=models.IntegerField(max_length=32),
        ),
    ]
