# Generated by Django 3.2 on 2022-11-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20221111_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv',
            field=models.IntegerField(max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='pan',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.IntegerField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='work',
            name='city',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='work',
            name='postalZip',
            field=models.CharField(max_length=128),
        ),
    ]
